// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NET1704_221_ASM3_SE170224_NguyenTruongThinh.Data.Models;

public partial class Ticket
{
    public int TicketId { get; set; }

    public string TicketName { get; set; }

    public string TicketType { get; set; }

    public decimal? Price { get; set; }

    public int? AvailableQuantity { get; set; }

    public DateTime? TimeStart { get; set; }

    public DateTime? TimeEnd { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public bool? Status { get; set; }
}